apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: overengineer-frontend
  labels:
spec:
  rules:
    - host: "overengineer.fsn.k8s.ciapa.tech"
      http:
        paths:
          - path: /
            backend:
              serviceName: overengineer-frontend
              servicePort: 8080
